name: ci 
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "GitHub Actions run ID from repo1"
        required: true
  repository_dispatch:
    types: [deploy-mkdocs]
jobs:
  download-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo2
        uses: actions/checkout@v4

      - name: Set RUN_ID
        run: echo "RUN_ID=${{ github.event.client_payload.run_id || inputs.run_id }}" >> $GITHUB_ENV

      - name: Download artifact from repo1
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-site
          github-token: ${{ secrets.PAT_BUILD_WORKFLOW }}
          run_id: ${{ env.RUN_ID }}
          repository: edfloresb/portfolio-private
